POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title" : "Bouvier'n perheen pää",
    "author" : "Maggie Simpson",
    "likes" : 10,
    "url" : "http://www.simpsonit.org/hahmot/clancy-bouvier/",
    "userId" : "5b2bc99b3cb4111eb8317038"
}