POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "App developers get their wish with expanded support for free trials",
    "author": "Sarah Perez",
    "url": "https://tcrn.ch/2LlULGR",
    "likes": 2304
}
